13 feat fetch hook 제작 ver1
2-2-22/rolling pull request #21
Opened 2024-02-27 07:54 UTC by bokeeeey

## #️⃣연관된 이슈

우선 `useFetch`의 기본적인 설계를 해 보았습니다.
하지만 테스트를 거치지 않은 상태여서 추후 작업에서 사용해보고 보완해 나가는것이 좋아보입니다.

## 📝작업 내용

url, method, body 를 파라미터로 전달받는 useFetch Hook 기초 설계

2024-02-27 08:27 UTC, devwqc approved these changes
훌륭합니다👍

2024-02-27 08:27 UTC, devwqc commented on src/hooks/useFetch.js
> +const baseURL = 'https://rolling-api.vercel.app';
baseURL은 상수니까 BASE_URL로 하면 더 좋을 것 같습니다!

2024-02-27 08:27 UTC, devwqc commented on src/hooks/useFetch.js
> +  const [isData, setIsData] = useState(null);
보통 변수 앞에 is나 has가 붙으면 `boolean` 값이 들어가 있다고 생각할 수 있어서 is는 지우는 것이 더 나을 거 같습니다
```suggestion
  const [data, setData] = useState(null);
```

2024-02-27 08:33 UTC, Chaemin-153 approved these changes
좋은 것 같습니다

2024-02-27 08:42 UTC, bokeeeey commented on src/hooks/useFetch.js
> +const baseURL = 'https://rolling-api.vercel.app';
자바스크립트에서 언더바 사용해도 괜찮을까요? 문제는 없지만 권고하는 스타일은 아닌듯해서 우선 저렇게 해 보았읍니다

2024-02-27 08:55 UTC, bokeeeey commented on src/hooks/useFetch.js
> +const baseURL = 'https://rolling-api.vercel.app';
수정 했읍이다

2024-02-27 11:22 UTC, kong33 requested changes

2024-02-27 11:22 UTC, kong33 commented on src/hooks/useFetch.js
> +  const [data, setData] = useState(null);
default 파라미터를 쓰려면 파라미터 중 맨 뒤로 넣어야 한다고 알고있는데 확인 부탁드려요!

2024-02-27 11:22 UTC, kong33 commented on src/hooks/useFetch.js
> +        if (!response.ok) {
👍

2024-02-27 11:22 UTC, kong33 commented on src/hooks/useFetch.js
> +  }, [url, method, body]);
body를 stringify 하셔서 문제 없을 것 같습니다! 👍

2024-02-28 01:33 UTC, Chaemin-153 commented on src/hooks/useFetch.js
> +  const [data, setData] = useState(null);
오 저도 이렇게 알고 있습니다!

2024-02-28 01:36 UTC, kong33 commented on src/hooks/useFetch.js
> +  const [data, setData] = useState(null);
수정하시면 알려주세요... 제가 approve 로 바꾸어야 하는군요..!

2024-02-28 10:42 UTC, bokeeeey commented on src/hooks/useFetch.js
> +  const [data, setData] = useState(null);
수정 완료했읍니다 확인 부탁드릴게요!

2024-02-28 11:02 UTC, kong33 commented on src/hooks/useFetch.js
> +  const [data, setData] = useState(null);
👍

2024-02-28 11:02 UTC, kong33 approved these changes
LGTM!

2024-02-28 11:10 UTC, jinah-dev approved these changes
멋지십니다!!

2024-02-28 11:14 UTC, merged